name: comment_on_pr

on:
  pull_request:
    branches: master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Create comments
      run: |
        npm install 
        npm run test:cov >> comments
        sed -i -z 's/\n/\\n/g' comments

    - name: Post multi-line comments
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        curl -X POST \
             -H "Authorization: token ${GITHUB_TOKEN}" \
             -d "{\"body\": \"```\n $(cat comments) \n``` \"}" \
             ${URL}
