name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - uses: actions/checkout@v2
    - name: npm install 
      run: npm install 
    - name: test github.actor
      run: echo ${{ github.actor }}
    - name: test secret
      run: echo  ${{ secrets.AWS_ACCESS_KEY_ID }}   ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: lint and test 
      run: |
        npm run lint
        npm run test 
#     - name: serverless deploy
#       uses: serverless/github-action@master
#       with:
#         args: deploy
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
