name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1.1.0
      with:
        version: 12.x
    - name: npm install 
      run: npm install 
    - name: lint and test 
      run: |
        npm run lint
        npm run test 
